project:
  type: website

website:
  title: "Roberto De Carolis<br><span class='site-subtitle'>Microbiology & Bioinformatics</span>"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects  
      - href: skills.qmd
        text: Skills
      - href: experience.qmd
        text: Experience
      - href: about.qmd
        text: About
      - href: cv
        text: CV
      

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-newwindow: true



