---
title: "Roberto De Carolis | PhD "
---
# Microbiology, Bioinformatic & Astrobiology

PhD biologist with experience in Microbiology, extremophiles, Fungi, micro algae, cyanobacteria and lichens, Antarctic research and microbial genomics.

## Research Interests

- Microbial genomics
- Bioinformatic
- Astrobiology
- Extremophiles
- Cyanobacteria
- Environmental Biology
- Ecology 

## Portfolio

This website collects my scientific projects, pubblication, bioinformatic analyses and my observation

### Current project

### Ecogenomics and Comparative Genomics of Chroococcidiopsidales

**Project status:** Ongoing  
**Last update:** September 2026

Ecogenomic investigation integrating genome-quality assessment, genome-based taxonomy, phylogenomics, comparative genomics and environmental metadata across *Chroococcidiopsis* and related extremophilic cyanobacterial lineages.

[View project](projects/chroococcidiopsales-ecogenomics/)

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
