## Peer-reviewed publications

My research focuses on microbial diversity, extremophiles, Antarctic ecosystems, lichen symbioses, molecular ecology and cyanobacterial adaptation. My work combines microbiology, molecular biology, microscopy, phylogenetics, genomics and bioinformatics.

### 2025

**De Carolis, R.**, Stoppiello, G.A., Turchetti, B., Bartolomeo, G., Coleine, C., Tretiach, M., ... & Muggia, L.  
**Cryptic associated fungi and algae isolated from Antarctic epilithic lichens of the Victoria Land and the description of five new fungal species.**  
*Persoonia – Molecular Phylogeny and Evolution of Fungi*, **55**(1), 439–476.  
**DOI:** 10.3114/persoonia.2025.55.11

<br>

Stoppiello, G.A., **De Carolis, R.**, Coleine, C., Tretiach, M., Muggia, L., & Selbmann, L.  
**Intrathalline fungal and bacterial diversity is uncovered in Antarctic lichen symbioses.**  
*Environmental Microbiology Reports*, **17**(3), e70080.  
**Equal contribution / co-first author**  
**DOI:** 10.1111/1758-2229.70080

<br>

Stoppiello, G.A., Muggia, L., **De Carolis, R.**, Coleine, C., & Selbmann, L.  
**Ecological niche drives fungal and bacterial diversity in endolithic and epilithic communities inhabiting granites in Victoria Land, Antarctica.**  
*Polar Biology*, **48**(1), 16.  
**DOI:** 10.1007/s00300-024-03328-8


### 2024

Cometto, A., Ametrano, C.G., **De Carolis, R.**, Leavitt, S.D., Grube, M., Pallavicini, A., & Muggia, L.  
**Highly heterogeneous mycobiota shape fungal diversity in two globally distributed lichens.**  
*Fungal Ecology*, **69**, 101331.  
**DOI:** 10.1016/j.funeco.2024.101331


### 2023

**De Carolis, R.**, Muggia, L., & Bacaro, G.  
**Lichen and lichenicolous fungal communities tested as suitable systems for the application of cross-taxon analysis.**  
*Diversity*, **15**, 285.  
**DOI:** 10.3390/d15020285

<br>

Sanders, W., **De Carolis, R.**, Ertz, D., de los Ríos, A., & Muggia, L.  
**Independent, structurally distinct transitions to microfruticose growth in the crustose genus Porina (Ostropales, Lecanoromycetes): new isidioid species from south-western Florida.**  
*The Lichenologist*, **55**(5), 347–365.  
**DOI:** 10.1017/S0024282923000440


### 2022

**De Carolis, R.**, Cometto, A., Moya, P., Barreno, E., Grube, M., Tretiach, M., Leavitt, S.D., & Muggia, L.  
**Photobiont diversity in lichen symbioses from extreme environments.**  
*Frontiers in Microbiology*, **13**.  
**DOI:** 10.3389/fmicb.2022.809804

<br>

Billi, D., Napoli, A., Mosca, C., Fagliarone, C., **De Carolis, R.**, Balbi, A., Scanu, M., Selinger, V.M., Antonaru, L.A., & Nürnberg, D.J.  
**Identification of far-red light acclimation in an endolithic Chroococcidiopsis strain and associated genomic features: implications for oxygenic photosynthesis on exoplanets.**  
*Frontiers in Microbiology*, **13**.  
**DOI:** 10.3389/fmicb.2022.933404


### 2021

Muggia, L., Coleine, C., **De Carolis, R.**, Cometto, A., & Selbmann, L.  
**Antarctolichenia onofrii gen. nov. sp. nov. from Antarctic endolithic communities untangles the evolution of rock-inhabiting and lichenized fungi in Arthoniomycetes.**  
*Journal of Fungi*, **7**, 935.  
**DOI:** 10.3390/jof7110935


## Research themes

Across these publications, my research contributions include:

- **Antarctic and extreme-environment microbiology**
- **Fungal and lichen biodiversity**
- **Microbial community ecology**
- **Molecular taxonomy and phylogenetics**
- **Lichen photobiont diversity**
- **Cyanobacterial adaptation to far-red light**
- **Genomics and sequence-based microbial characterization**
- **Description and characterization of novel fungal taxa**