<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>index – Roberto De Carolis | Microbiology &amp; Bioinformatic</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0c31ab49677ad708b94a91a164fb2618.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Roberto De Carolis | Microbiology &amp; Bioinformatic</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../skills.html"> 
<span class="menu-text">Skills</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#project-overview" id="toc-project-overview" class="nav-link active" data-scroll-target="#project-overview">Project overview</a></li>
  <li><a href="#project-objectives" id="toc-project-objectives" class="nav-link" data-scroll-target="#project-objectives">Project objectives</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key findings</a></li>
  <li><a href="#read-preprocessing-and-quality-filtering" id="toc-read-preprocessing-and-quality-filtering" class="nav-link" data-scroll-target="#read-preprocessing-and-quality-filtering">Read preprocessing and quality filtering</a>
  <ul class="collapse">
  <li><a href="#raw-sequencing-data" id="toc-raw-sequencing-data" class="nav-link" data-scroll-target="#raw-sequencing-data">Raw sequencing data</a></li>
  <li><a href="#filtering-results" id="toc-filtering-results" class="nav-link" data-scroll-target="#filtering-results">Filtering results</a></li>
  <li><a href="#read-preprocessing-interpretation" id="toc-read-preprocessing-interpretation" class="nav-link" data-scroll-target="#read-preprocessing-interpretation">Read-preprocessing interpretation</a></li>
  </ul></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a>
  <ul class="collapse">
  <li><a href="#original-publication" id="toc-original-publication" class="nav-link" data-scroll-target="#original-publication">Original publication</a></li>
  </ul></li>
  <li><a href="#taxonomic-assessment" id="toc-taxonomic-assessment" class="nav-link" data-scroll-target="#taxonomic-assessment">Taxonomic assessment</a>
  <ul class="collapse">
  <li><a href="#kraken2-results" id="toc-kraken2-results" class="nav-link" data-scroll-target="#kraken2-results">Kraken2 results</a></li>
  <li><a href="#taxonomic-interpretation" id="toc-taxonomic-interpretation" class="nav-link" data-scroll-target="#taxonomic-interpretation">Taxonomic interpretation</a></li>
  </ul></li>
  <li><a href="#de-novo-genome-assembly-and-quality-assessment" id="toc-de-novo-genome-assembly-and-quality-assessment" class="nav-link" data-scroll-target="#de-novo-genome-assembly-and-quality-assessment">De novo genome assembly and quality assessment</a>
  <ul class="collapse">
  <li><a href="#assembly-statistics" id="toc-assembly-statistics" class="nav-link" data-scroll-target="#assembly-statistics">Assembly statistics</a></li>
  <li><a href="#assembly-quality-interpretation" id="toc-assembly-quality-interpretation" class="nav-link" data-scroll-target="#assembly-quality-interpretation">Assembly-quality interpretation</a></li>
  </ul></li>
  <li><a href="#read-mapping-and-chromosome-coverage" id="toc-read-mapping-and-chromosome-coverage" class="nav-link" data-scroll-target="#read-mapping-and-chromosome-coverage">Read mapping and chromosome coverage</a>
  <ul class="collapse">
  <li><a href="#mapping-statistics" id="toc-mapping-statistics" class="nav-link" data-scroll-target="#mapping-statistics">Mapping statistics</a></li>
  <li><a href="#coverage-assessment" id="toc-coverage-assessment" class="nav-link" data-scroll-target="#coverage-assessment">Coverage assessment</a></li>
  <li><a href="#mapping-and-coverage-interpretation" id="toc-mapping-and-coverage-interpretation" class="nav-link" data-scroll-target="#mapping-and-coverage-interpretation">Mapping and coverage interpretation</a></li>
  </ul></li>
  <li><a href="#plasmid-reconstruction-and-mobile-elements" id="toc-plasmid-reconstruction-and-mobile-elements" class="nav-link" data-scroll-target="#plasmid-reconstruction-and-mobile-elements">Plasmid reconstruction and mobile elements</a>
  <ul class="collapse">
  <li><a href="#candidate-plasmids" id="toc-candidate-plasmids" class="nav-link" data-scroll-target="#candidate-plasmids">Candidate plasmids</a></li>
  <li><a href="#plasmid-reconstruction-interpretation" id="toc-plasmid-reconstruction-interpretation" class="nav-link" data-scroll-target="#plasmid-reconstruction-interpretation">Plasmid reconstruction interpretation</a></li>
  </ul></li>
  <li><a href="#species-confirmation-by-average-nucleotide-identity" id="toc-species-confirmation-by-average-nucleotide-identity" class="nav-link" data-scroll-target="#species-confirmation-by-average-nucleotide-identity">Species confirmation by average nucleotide identity</a>
  <ul class="collapse">
  <li><a href="#ani-results" id="toc-ani-results" class="nav-link" data-scroll-target="#ani-results">ANI results</a></li>
  <li><a href="#species-identification-interpretation" id="toc-species-identification-interpretation" class="nav-link" data-scroll-target="#species-identification-interpretation">Species-identification interpretation</a></li>
  </ul></li>
  <li><a href="#genome-annotation" id="toc-genome-annotation" class="nav-link" data-scroll-target="#genome-annotation">Genome annotation</a>
  <ul class="collapse">
  <li><a href="#annotation-summary" id="toc-annotation-summary" class="nav-link" data-scroll-target="#annotation-summary">Annotation summary</a></li>
  <li><a href="#annotation-interpretation" id="toc-annotation-interpretation" class="nav-link" data-scroll-target="#annotation-interpretation">Annotation interpretation</a></li>
  </ul></li>
  <li><a href="#genomic-safety-assessment" id="toc-genomic-safety-assessment" class="nav-link" data-scroll-target="#genomic-safety-assessment">Genomic safety assessment</a>
  <ul class="collapse">
  <li><a href="#antimicrobial-resistance" id="toc-antimicrobial-resistance" class="nav-link" data-scroll-target="#antimicrobial-resistance">Antimicrobial resistance</a></li>
  <li><a href="#virulence-associated-genes" id="toc-virulence-associated-genes" class="nav-link" data-scroll-target="#virulence-associated-genes">Virulence-associated genes</a></li>
  <li><a href="#biogenic-amine-pathways" id="toc-biogenic-amine-pathways" class="nav-link" data-scroll-target="#biogenic-amine-pathways">Biogenic amine pathways</a></li>
  <li><a href="#prophage-associated-regions" id="toc-prophage-associated-regions" class="nav-link" data-scroll-target="#prophage-associated-regions">Prophage-associated regions</a></li>
  <li><a href="#plasmid-associated-safety-screening" id="toc-plasmid-associated-safety-screening" class="nav-link" data-scroll-target="#plasmid-associated-safety-screening">Plasmid-associated safety screening</a></li>
  <li><a href="#genomic-safety-interpretation" id="toc-genomic-safety-interpretation" class="nav-link" data-scroll-target="#genomic-safety-interpretation">Genomic-safety interpretation</a></li>
  </ul></li>
  <li><a href="#functional-and-technological-characterization" id="toc-functional-and-technological-characterization" class="nav-link" data-scroll-target="#functional-and-technological-characterization">Functional and technological characterization</a>
  <ul class="collapse">
  <li><a href="#plantaricin-associated-locus" id="toc-plantaricin-associated-locus" class="nav-link" data-scroll-target="#plantaricin-associated-locus">Plantaricin-associated locus</a></li>
  <li><a href="#locus-organization" id="toc-locus-organization" class="nav-link" data-scroll-target="#locus-organization">Locus organization</a></li>
  <li><a href="#stress-tolerance" id="toc-stress-tolerance" class="nav-link" data-scroll-target="#stress-tolerance">Stress tolerance</a></li>
  <li><a href="#stress-response-interpretation" id="toc-stress-response-interpretation" class="nav-link" data-scroll-target="#stress-response-interpretation">Stress-response interpretation</a></li>
  <li><a href="#carbohydrate-utilization" id="toc-carbohydrate-utilization" class="nav-link" data-scroll-target="#carbohydrate-utilization">Carbohydrate utilization</a></li>
  <li><a href="#carbohydrate-utilization-interpretation" id="toc-carbohydrate-utilization-interpretation" class="nav-link" data-scroll-target="#carbohydrate-utilization-interpretation">Carbohydrate-utilization interpretation</a></li>
  <li><a href="#adhesion-and-cell-surface-interaction" id="toc-adhesion-and-cell-surface-interaction" class="nav-link" data-scroll-target="#adhesion-and-cell-surface-interaction">Adhesion and cell-surface interaction</a></li>
  <li><a href="#adhesion-and-cell-surface-interpretation" id="toc-adhesion-and-cell-surface-interpretation" class="nav-link" data-scroll-target="#adhesion-and-cell-surface-interpretation">Adhesion and cell-surface interpretation</a></li>
  <li><a href="#exopolysaccharide-and-surface-polysaccharide-potential" id="toc-exopolysaccharide-and-surface-polysaccharide-potential" class="nav-link" data-scroll-target="#exopolysaccharide-and-surface-polysaccharide-potential">Exopolysaccharide and surface-polysaccharide potential</a></li>
  <li><a href="#exopolysaccharide-interpretation" id="toc-exopolysaccharide-interpretation" class="nav-link" data-scroll-target="#exopolysaccharide-interpretation">Exopolysaccharide interpretation</a></li>
  <li><a href="#technological-traits" id="toc-technological-traits" class="nav-link" data-scroll-target="#technological-traits">Technological traits</a></li>
  <li><a href="#technological-traits-interpretation" id="toc-technological-traits-interpretation" class="nav-link" data-scroll-target="#technological-traits-interpretation">Technological-traits interpretation</a></li>
  </ul></li>
  <li><a href="#comparative-genomics" id="toc-comparative-genomics" class="nav-link" data-scroll-target="#comparative-genomics">Comparative genomics</a>
  <ul class="collapse">
  <li><a href="#pangenome-structure" id="toc-pangenome-structure" class="nav-link" data-scroll-target="#pangenome-structure">Pangenome structure</a></li>
  <li><a href="#strain-specific-gene-clusters" id="toc-strain-specific-gene-clusters" class="nav-link" data-scroll-target="#strain-specific-gene-clusters">Strain-specific gene clusters</a></li>
  <li><a href="#surface-polysaccharide-diversification" id="toc-surface-polysaccharide-diversification" class="nav-link" data-scroll-target="#surface-polysaccharide-diversification">Surface-polysaccharide diversification</a></li>
  <li><a href="#plantaricin-locus-conservation" id="toc-plantaricin-locus-conservation" class="nav-link" data-scroll-target="#plantaricin-locus-conservation">Plantaricin locus conservation</a></li>
  <li><a href="#adhesion-associated-proteins" id="toc-adhesion-associated-proteins" class="nav-link" data-scroll-target="#adhesion-associated-proteins">Adhesion-associated proteins</a></li>
  <li><a href="#e2c2-specific-β-glucoside-utilization-module" id="toc-e2c2-specific-β-glucoside-utilization-module" class="nav-link" data-scroll-target="#e2c2-specific-β-glucoside-utilization-module">E2C2-specific β-glucoside utilization module</a></li>
  <li><a href="#dicarboxylate-associated-metabolic-module" id="toc-dicarboxylate-associated-metabolic-module" class="nav-link" data-scroll-target="#dicarboxylate-associated-metabolic-module">Dicarboxylate-associated metabolic module</a></li>
  <li><a href="#mobile-and-prophage-associated-diversity" id="toc-mobile-and-prophage-associated-diversity" class="nav-link" data-scroll-target="#mobile-and-prophage-associated-diversity">Mobile and prophage-associated diversity</a></li>
  <li><a href="#comparative-interpretation" id="toc-comparative-interpretation" class="nav-link" data-scroll-target="#comparative-interpretation">Comparative interpretation</a></li>
  </ul></li>
  <li><a href="#workflow-design" id="toc-workflow-design" class="nav-link" data-scroll-target="#workflow-design">Workflow design</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<table class="caption-top table">
<tbody>
<tr class="odd">
<td>title: “Sacco Lab Analysis”</td>
</tr>
</tbody>
</table>
<section id="project-overview" class="level2">
<h2 class="anchored" data-anchor-id="project-overview">Project overview</h2>
<p>This project presents an independent, reproducible genomic characterization of <em>Lactiplantibacillus plantarum</em> E2C2 using publicly available Illumina whole-genome sequencing data.</p>
<p>The analysis integrates read quality control, taxonomic assessment, de novo genome assembly, genome-quality evaluation, chromosome and plasmid reconstruction, species confirmation, functional annotation, genomic safety screening and comparative genomics.</p>
<p>Particular attention was given to traits relevant to food biotechnology and potential probiotic applications, including bacteriocin-associated loci, stress-response systems, carbohydrate utilization, adhesion-associated proteins, exopolysaccharide biosynthesis and fermentation-related metabolic functions.</p>
<p>The complete analysis was implemented as a modular <strong>Snakemake workflow</strong> using isolated Conda environments to support reproducibility and dependency management.</p>
</section>
<section id="project-objectives" class="level2">
<h2 class="anchored" data-anchor-id="project-objectives">Project objectives</h2>
<p>The project was designed to:</p>
<ul>
<li>reconstruct and evaluate the E2C2 genome from public Illumina sequencing data</li>
<li>confirm its taxonomic identity using complementary read- and genome-level approaches</li>
<li>distinguish chromosome- and plasmid-associated genomic components</li>
<li>assess genome completeness, contamination and annotation quality</li>
<li>investigate genomic safety-related features</li>
<li>characterize functional traits relevant to stress adaptation, antimicrobial competition, carbohydrate metabolism, adhesion and polysaccharide biosynthesis</li>
<li>investigate technological traits relevant to fermentation</li>
<li>compare E2C2 with additional <em>L. plantarum</em> strains to distinguish conserved and strain-variable genomic features</li>
<li>integrate the complete analysis into a reproducible Snakemake workflow</li>
</ul>
</section>
<section id="key-findings" class="level2">
<h2 class="anchored" data-anchor-id="key-findings">Key findings</h2>
<p>The integrated genomic analysis of <em>Lactiplantibacillus plantarum</em> E2C2 highlighted several major features:</p>
<ul>
<li><strong>Species identity confirmed:</strong> whole-genome ANI showed <strong>99.01% identity to <em>L. plantarum</em></strong>, clearly separating E2C2 from closely related species.</li>
<li><strong>High-quality genome reconstruction:</strong> the assembly reached <strong>100% estimated completeness</strong>, with an <strong>N50 of 271,950 bp</strong>.</li>
<li><strong>Favourable genomic safety profile:</strong> no reportable antimicrobial-resistance determinants, major virulence factors or major biogenic-amine pathways were detected in the targeted screening.</li>
<li><strong>Plantaricin-associated potential:</strong> E2C2 carries a highly conserved plantaricin locus containing regulatory, immunity and bacteriocin-associated components, including <strong>PlnEF</strong> and <strong>PlnJK</strong>.</li>
<li><strong>Stress-adaptation repertoire:</strong> the genome encodes multiple heat-shock, proteostasis, redox, acid-stress and bile-associated functions.</li>
<li><strong>Surface and EPS potential:</strong> several adhesion-associated proteins and <strong>three candidate polysaccharide biosynthesis clusters</strong> were identified, including <strong>two high-confidence EPS-associated loci</strong>.</li>
<li><strong>Fermentation-related metabolism:</strong> E2C2 carries genomic capacity for L- and D-lactate metabolism, acetoin-associated metabolism and extensive peptide uptake and intracellular proteolysis.</li>
<li><strong>Substantial accessory-genome diversity:</strong> comparative analysis with strains A6 and B21 identified <strong>273 E2C2-specific gene clusters</strong>, including variable EPS-associated, β-glucoside-utilization, dicarboxylate-metabolism and mobile-element modules.</li>
</ul>
</section>
<section id="read-preprocessing-and-quality-filtering" class="level2">
<h2 class="anchored" data-anchor-id="read-preprocessing-and-quality-filtering">Read preprocessing and quality filtering</h2>
<p>Raw Illumina paired-end reads were processed using <strong>fastp 1.3.6</strong>, followed by quality assessment using <strong>FastQC 0.12.1</strong> and aggregation of the final reports with <strong>MultiQC</strong>.</p>
<section id="raw-sequencing-data" class="level3">
<h3 class="anchored" data-anchor-id="raw-sequencing-data">Raw sequencing data</h3>
<p>Before filtering, the dataset contained:</p>
<ul>
<li><strong>Total reads:</strong> 3,291,512</li>
<li><strong>Total bases:</strong> 654,679,422 bp</li>
<li><strong>Q20 bases:</strong> 84.70%</li>
<li><strong>Q30 bases:</strong> 72.82%</li>
<li><strong>Mean R1 length:</strong> 196 bp</li>
<li><strong>Mean R2 length:</strong> 201 bp</li>
<li><strong>GC content:</strong> 43.60%</li>
</ul>
</section>
<section id="filtering-results" class="level3">
<h3 class="anchored" data-anchor-id="filtering-results">Filtering results</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Raw reads</th>
<th style="text-align: right;">Filtered reads</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total reads</td>
<td style="text-align: right;">3,291,512</td>
<td style="text-align: right;">2,143,970</td>
</tr>
<tr class="even">
<td>Total bases</td>
<td style="text-align: right;">654,679,422</td>
<td style="text-align: right;">408,347,089</td>
</tr>
<tr class="odd">
<td>Q20 bases</td>
<td style="text-align: right;">84.70%</td>
<td style="text-align: right;">96.55%</td>
</tr>
<tr class="even">
<td>Q30 bases</td>
<td style="text-align: right;">72.82%</td>
<td style="text-align: right;">88.37%</td>
</tr>
<tr class="odd">
<td>Mean read length R1</td>
<td style="text-align: right;">196 bp</td>
<td style="text-align: right;">201.7 bp</td>
</tr>
<tr class="even">
<td>Mean read length R2</td>
<td style="text-align: right;">201 bp</td>
<td style="text-align: right;">179.2 bp</td>
</tr>
<tr class="odd">
<td>GC content</td>
<td style="text-align: right;">43.60%</td>
<td style="text-align: right;">43.17%</td>
</tr>
<tr class="even">
<td>Duplication rate</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">0.94%</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Reads removed during filtering included:</p>
<p><br></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Filtering outcome</th>
<th style="text-align: right;">Reads</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reads passing filters</td>
<td style="text-align: right;">2,143,970</td>
</tr>
<tr class="even">
<td>Reads too short</td>
<td style="text-align: right;">1,123,774</td>
</tr>
<tr class="odd">
<td>Low-quality reads</td>
<td style="text-align: right;">23,566</td>
</tr>
<tr class="even">
<td>Reads with too many N bases</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Adapter-dimer reads</td>
<td style="text-align: right;">196</td>
</tr>
</tbody>
</table>
</section>
<section id="read-preprocessing-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="read-preprocessing-interpretation">Read-preprocessing interpretation</h3>
<p>Preprocessing substantially improved the overall quality of the sequencing dataset.</p>
<p>The proportion of bases reaching <strong>Q20 increased from 84.70% to 96.55%</strong>, while <strong>Q30 increased from 72.82% to 88.37%</strong>.</p>
<p>Approximately <strong>65% of the original reads</strong> were retained. Most rejected reads were removed because they fell below the minimum retained length after trimming, rather than because of globally poor sequence quality.</p>
<p>The GC content remained highly stable before and after preprocessing (<strong>43.60% vs 43.17%</strong>), indicating that filtering did not substantially alter the overall nucleotide composition of the dataset.</p>
<p>The final paired-end reads showed different mean lengths, with approximately <strong>201.7 bp for R1</strong> and <strong>179.2 bp for R2</strong>, reflecting more extensive trimming of the reverse reads.</p>
<p>A dedicated MultiQC report was generated using only the final preprocessing outputs to avoid mixing exploratory trimming tests with the definitive workflow results.</p>
</section>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>This project uses publicly available whole-genome sequencing data from <em>Lactiplantibacillus plantarum</em> strain <strong>E2C2</strong>, originally isolated from the human gut.</p>
<p>The sequencing data were retrieved from the European Nucleotide Archive (ENA) and independently reanalysed as part of this portfolio project.</p>
<ul>
<li><strong>Strain:</strong> E2C2</li>
<li><strong>Species:</strong> <em>Lactiplantibacillus plantarum</em></li>
<li><strong>Run accession:</strong> ERR1158396</li>
<li><strong>Study accession:</strong> PRJEB11980</li>
<li><strong>Sample accession:</strong> SAMEA3684370</li>
<li><strong>Experiment accession:</strong> ERX1231803</li>
<li><strong>Sequencing platform:</strong> Illumina MiSeq</li>
<li><strong>Library layout:</strong> Paired-end</li>
<li><strong>Sequencing strategy:</strong> Whole Genome Sequencing (WGS)</li>
<li><strong>Library source:</strong> Genomic DNA</li>
<li><strong>Number of paired-end reads:</strong> 1,645,756</li>
<li><strong>Total reads (R1 + R2):</strong> 3,291,512</li>
<li><strong>Total sequenced bases:</strong> 654,679,422 bp</li>
<li><strong>Original study:</strong> <em>WGS of Lactobacillus plantarum isolated from human gut</em></li>
<li><strong>Depositing institution:</strong> Justus Liebig University</li>
</ul>
<p>The two paired-end FASTQ files used in the analysis were stored locally as:</p>
<pre class="text"><code>E2C2_R1.fastq.gz
E2C2_R2.fastq.gz</code></pre>
<p>with compressed file sizes of approximately <strong>252 MB</strong> and <strong>280 MB</strong>, respectively.</p>
<p>The raw sequencing data and the original experimental work were not generated as part of this portfolio project. My contribution consists of the independent computational reanalysis, workflow development, genomic characterization, interpretation and documentation of the publicly available dataset.</p>
<section id="original-publication" class="level3">
<h3 class="anchored" data-anchor-id="original-publication">Original publication</h3>
<p>The E2C2 strain was previously described in:</p>
<p><strong>Suryavanshi MV, Paul D, Doijad SP, Bhute SS, Hingamire TB, Gune RP, et al.</strong><br>
<em>Draft genome sequence of Lactobacillus plantarum strains E2C2 and E2C5 isolated from human stool culture.</em><br>
Standards in Genomic Sciences, 2017.</p>
<p>The published E2C2 draft genome was approximately <strong>3.60 Mb</strong>, with a reported <strong>GC content of 43.99%</strong>.</p>
<p>These published values provide an external reference against which the independently reconstructed genome can be compared.</p>
</section>
</section>
<section id="taxonomic-assessment" class="level2">
<h2 class="anchored" data-anchor-id="taxonomic-assessment">Taxonomic assessment</h2>
<p>Taxonomic classification of the quality-filtered sequencing reads was performed using <strong>Kraken2</strong> to evaluate whether the dataset was consistent with the expected taxonomic identity of the E2C2 strain and to identify potential evidence of contamination.</p>
<section id="kraken2-results" class="level3">
<h3 class="anchored" data-anchor-id="kraken2-results">Kraken2 results</h3>
<p>The main taxonomic assignments were:</p>
<ul>
<li><strong>Classified sequences:</strong> 91.78%</li>
<li><strong>Unclassified sequences:</strong> 8.22%</li>
<li><strong>Lactobacillaceae:</strong> 90.18%</li>
<li><strong>Lactiplantibacillus:</strong> 79.72%</li>
<li><strong><em>Lactiplantibacillus plantarum</em>:</strong> 40.06%</li>
<li><strong><em>L. plantarum</em> clade assignments:</strong> 429,468</li>
</ul>
<p>Most classified sequences were therefore assigned within the expected lactic-acid-bacterium lineage.</p>
<p>At species level, <em>Lactiplantibacillus plantarum</em> represented the dominant assignment. Smaller fractions were assigned to closely related species, including <em>Lactiplantibacillus argentoratensis</em>, <em>Lactiplantibacillus pentosus</em> and <em>Lactiplantibacillus paraplantarum</em>.</p>
</section>
<section id="taxonomic-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="taxonomic-interpretation">Taxonomic interpretation</h3>
<p>The taxonomic profile was strongly consistent with the expected identity of the E2C2 dataset.</p>
<p>More than <strong>90% of classified sequences belonged to Lactobacillaceae</strong>, while approximately <strong>80% were assigned to the genus Lactiplantibacillus</strong>.</p>
<p>The lower proportion assigned directly to <em>L. plantarum</em> at species level should not be interpreted as evidence that only 40% of the dataset originated from this species. Read-level k-mer classifiers such as Kraken2 may assign sequences from closely related taxa to higher taxonomic ranks when species-specific sequence information is insufficient.</p>
<p>For this reason, Kraken2 was used primarily as an initial taxonomic and contamination-screening step. Species identity was subsequently evaluated using genome-level approaches after de novo assembly.</p>
</section>
</section>
<section id="de-novo-genome-assembly-and-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="de-novo-genome-assembly-and-quality-assessment">De novo genome assembly and quality assessment</h2>
<p>The quality-filtered paired-end reads were assembled de novo using <strong>SPAdes 3.15.5</strong> in careful mode.</p>
<p>The assembly was generated using automatic k-mer selection, 4 CPU threads and an 8 GB memory limit.</p>
<section id="assembly-statistics" class="level3">
<h3 class="anchored" data-anchor-id="assembly-statistics">Assembly statistics</h3>
<p>Assembly quality was assessed using <strong>QUAST 5.3.0</strong>.</p>
<p>The main assembly metrics were:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total assembly length</td>
<td style="text-align: right;">3,771,999 bp</td>
</tr>
<tr class="even">
<td>Number of contigs</td>
<td style="text-align: right;">172</td>
</tr>
<tr class="odd">
<td>Contigs ≥1 kb</td>
<td style="text-align: right;">59</td>
</tr>
<tr class="even">
<td>Contigs ≥10 kb</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td>Contigs ≥50 kb</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td>Largest contig</td>
<td style="text-align: right;">619,211 bp</td>
</tr>
<tr class="odd">
<td>N50</td>
<td style="text-align: right;">271,950 bp</td>
</tr>
<tr class="even">
<td>N90</td>
<td style="text-align: right;">50,973 bp</td>
</tr>
<tr class="odd">
<td>L50</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>L90</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td>GC content</td>
<td style="text-align: right;">43.99%</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Genome-quality estimates:</p>
<p><br></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quality metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimated completeness</td>
<td style="text-align: right;">100%</td>
</tr>
<tr class="even">
<td>Estimated contamination</td>
<td style="text-align: right;">4.77%</td>
</tr>
<tr class="odd">
<td>CheckM2 genome size</td>
<td style="text-align: right;">3,799,521 bp</td>
</tr>
<tr class="even">
<td>Coding density</td>
<td style="text-align: right;">84.2%</td>
</tr>
<tr class="odd">
<td>Predicted CDSs</td>
<td style="text-align: right;">3,769</td>
</tr>
</tbody>
</table>
</section>
<section id="assembly-quality-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="assembly-quality-interpretation">Assembly-quality interpretation</h3>
<p>The independently reconstructed E2C2 genome showed a high degree of continuity, with an <strong>N50 of approximately 272 kb</strong> and only five contigs required to account for half of the assembled sequence.</p>
<p>The reconstructed genome size of approximately <strong>3.8 Mb</strong> and the <strong>43.99% GC content</strong> were highly consistent with the previously published E2C2 draft genome, which was reported to be approximately 3.60 Mb with a GC content of 43.99%.</p>
<p>CheckM2 estimated the genome to be essentially complete, although the <strong>4.77% contamination estimate</strong> indicates that the assembly should not be interpreted as completely free of potentially redundant or taxonomically discordant sequence.</p>
<p>This result motivated additional genome-level taxonomic assessment and inspection of chromosomal and plasmid-associated sequences in subsequent stages of the analysis.</p>
</section>
</section>
<section id="read-mapping-and-chromosome-coverage" class="level2">
<h2 class="anchored" data-anchor-id="read-mapping-and-chromosome-coverage">Read mapping and chromosome coverage</h2>
<p>Quality-filtered paired-end reads were mapped against the chromosome-associated assembly to evaluate read support and coverage across the reconstructed genome.</p>
<section id="mapping-statistics" class="level3">
<h3 class="anchored" data-anchor-id="mapping-statistics">Mapping statistics</h3>
<p>The alignment produced the following results:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Mapping metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Primary reads</td>
<td style="text-align: right;">2,143,970</td>
</tr>
<tr class="even">
<td>Primary mapped reads</td>
<td style="text-align: right;">1,926,527</td>
</tr>
<tr class="odd">
<td>Primary mapping rate</td>
<td style="text-align: right;">89.86%</td>
</tr>
<tr class="even">
<td>Total mapped alignments</td>
<td style="text-align: right;">1,950,902</td>
</tr>
<tr class="odd">
<td>Overall mapping rate</td>
<td style="text-align: right;">89.97%</td>
</tr>
<tr class="even">
<td>Properly paired reads</td>
<td style="text-align: right;">1,897,666</td>
</tr>
<tr class="odd">
<td>Proper-pair rate</td>
<td style="text-align: right;">88.51%</td>
</tr>
<tr class="even">
<td>Singletons</td>
<td style="text-align: right;">4,873</td>
</tr>
<tr class="odd">
<td>Singleton rate</td>
<td style="text-align: right;">0.23%</td>
</tr>
</tbody>
</table>
</section>
<section id="coverage-assessment" class="level3">
<h3 class="anchored" data-anchor-id="coverage-assessment">Coverage assessment</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Coverage feature</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Major contigs</td>
<td>Broadly covered across their full length</td>
</tr>
<tr class="even">
<td>Typical depth</td>
<td>Approximately 80-115× on major contigs</td>
</tr>
<tr class="odd">
<td>NODE_3</td>
<td>High apparent coverage but low mapping quality, consistent with a repetitive or structurally ambiguous region</td>
</tr>
</tbody>
</table>
<p><br><br> Examples include:</p>
<ul>
<li><strong>NODE_1 (619,211 bp):</strong> mean depth ~103×</li>
<li><strong>NODE_2 (422,966 bp):</strong> mean depth ~90×</li>
<li><strong>NODE_4 (283,149 bp):</strong> mean depth ~96×</li>
<li><strong>NODE_5 (271,950 bp):</strong> mean depth ~85×</li>
<li><strong>NODE_6 (255,977 bp):</strong> mean depth ~90×</li>
<li><strong>NODE_7 (235,913 bp):</strong> mean depth ~80×</li>
<li><strong>NODE_8 (207,316 bp):</strong> mean depth ~89×</li>
<li><strong>NODE_10 (144,027 bp):</strong> mean depth ~102×</li>
</ul>
</section>
<section id="mapping-and-coverage-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="mapping-and-coverage-interpretation">Mapping and coverage interpretation</h3>
<p>Approximately <strong>90% of the quality-filtered reads mapped back to the chromosome-associated assembly</strong>, with <strong>88.51% mapping as proper pairs</strong>.</p>
<p>Together with the high sequencing depth and complete coverage of the major contigs, these results provide strong read-level support for the reconstructed chromosome.</p>
<p>Coverage was not completely uniform across the assembly. Some smaller contigs showed substantially elevated depth, which may reflect repetitive regions, copy-number variation or sequences with different genomic abundance.</p>
<p>In addition, one large contig, <strong>NODE_3</strong>, showed high sequence coverage but an unusually low mean mapping quality despite substantial read depth. This suggests that many reads mapping to this region may also align well elsewhere in the assembly, and the region therefore requires cautious interpretation.</p>
</section>
</section>
<section id="plasmid-reconstruction-and-mobile-elements" class="level2">
<h2 class="anchored" data-anchor-id="plasmid-reconstruction-and-mobile-elements">Plasmid reconstruction and mobile elements</h2>
<p>The de novo assembly was further analysed using <strong>MOB-suite</strong> to distinguish chromosome-associated contigs from putative plasmid-associated sequences.</p>
<p>MOB-suite reconstructed a main chromosome-associated component and identified <strong>five candidate plasmid components</strong>.</p>
<section id="candidate-plasmids" class="level3">
<h3 class="anchored" data-anchor-id="candidate-plasmids">Candidate plasmids</h3>
<p>The reconstructed plasmid-associated components were:</p>
<ul>
<li><strong>AB793:</strong> 65,149 bp, 11 contigs — predicted as <strong>mobilizable</strong></li>
<li><strong>novel_b355…:</strong> 56,904 bp, 2 contigs — predicted as <strong>conjugative</strong></li>
<li><strong>AD789:</strong> 21,636 bp, 3 contigs — predicted as <strong>mobilizable</strong></li>
<li><strong>novel_777…:</strong> 10,959 bp, 2 contigs — predicted as <strong>mobilizable</strong></li>
<li><strong>AE885:</strong> 9,298 bp, 2 contigs — predicted as <strong>non-mobilizable</strong></li>
</ul>
<p>Several of these components contained plasmid-associated markers such as replicons and relaxases.</p>
<p>The approximately <strong>56.9 kb novel_b355 component</strong> showed the strongest evidence of autonomous mobility, containing:</p>
<ul>
<li>a plasmid replicon</li>
<li><strong>MOBQ</strong> relaxase-associated signatures</li>
<li>an <strong>MPF_T</strong> mating-pair formation system</li>
<li>a predicted <strong>conjugative</strong> mobility classification</li>
</ul>
<p>Its closest Mash neighbour in the MOB-suite database was associated with <em>Lactiplantibacillus plantarum</em>.</p>
</section>
<section id="plasmid-reconstruction-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="plasmid-reconstruction-interpretation">Plasmid reconstruction interpretation</h3>
<p>The MOB-suite results indicate that part of the E2C2 accessory genome is likely associated with plasmid-derived sequences.</p>
<p>Importantly, these components should not automatically be interpreted as contamination. Plasmids are biologically relevant components of bacterial genomes and may carry genes involved in adaptation, metabolism, stress response or horizontal gene transfer.</p>
<p>The identification of plasmid-associated contigs also provided a plausible explanation for some of the elevated sequencing-depth patterns observed during coverage analysis.</p>
<p>Because MOB-suite reconstructs plasmid candidates computationally from draft assemblies, the five components are reported here as <strong>putative plasmid-associated replicons rather than experimentally confirmed complete plasmids</strong>.</p>
</section>
</section>
<section id="species-confirmation-by-average-nucleotide-identity" class="level2">
<h2 class="anchored" data-anchor-id="species-confirmation-by-average-nucleotide-identity">Species confirmation by average nucleotide identity</h2>
<p>Genome-level taxonomic identification was performed using <strong>fastANI 1.34</strong>.</p>
<p>The E2C2 assembly was compared against reference genomes from three closely related species:</p>
<ul>
<li><em>Lactiplantibacillus plantarum</em></li>
<li><em>Lactiplantibacillus paraplantarum</em></li>
<li><em>Lactiplantibacillus pentosus</em></li>
</ul>
<section id="ani-results" class="level3">
<h3 class="anchored" data-anchor-id="ani-results">ANI results</h3>
<p>The genome-wide comparisons produced:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Reference species</th>
<th style="text-align: right;">ANI to E2C2</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Lactiplantibacillus plantarum</em></td>
<td style="text-align: right;">99.01%</td>
<td>Strong species-level match</td>
</tr>
<tr class="even">
<td><em>Lactiplantibacillus paraplantarum</em></td>
<td style="text-align: right;">87.73%</td>
<td>Clearly below species-level identity</td>
</tr>
<tr class="odd">
<td><em>Lactiplantibacillus pentosus</em></td>
<td style="text-align: right;">82.81%</td>
<td>Clearly below species-level identity</td>
</tr>
</tbody>
</table>
<p><br><br></p>
<p>For the <em>L. plantarum</em> comparison, fastANI identified matching sequence across 985 of 1,223 query fragments used in the analysis.</p>
</section>
<section id="species-identification-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="species-identification-interpretation">Species-identification interpretation</h3>
<p>The E2C2 genome showed a clear and substantially higher nucleotide identity to the <em>L. plantarum</em> reference genome than to the other closely related species tested.</p>
<p>An ANI of approximately <strong>99.01%</strong> strongly supports assignment of E2C2 to <em>Lactiplantibacillus plantarum</em>.</p>
<p>This genome-level result was consistent with the earlier Kraken2 read classification, but provided substantially greater species-level resolution.</p>
<p>Together, read-level taxonomic profiling, genome composition and whole-genome ANI therefore provided independent lines of evidence supporting the taxonomic identification of E2C2 as <em>Lactiplantibacillus plantarum</em>.</p>
</section>
</section>
<section id="genome-annotation" class="level2">
<h2 class="anchored" data-anchor-id="genome-annotation">Genome annotation</h2>
<p>The chromosome-associated component reconstructed by MOB-suite was functionally annotated using <strong>Bakta 1.12.1</strong> with the <strong>Bakta light database v6.0</strong>.</p>
<p>The annotation was integrated directly into the Snakemake workflow, ensuring that downstream safety and functional analyses used the same standardized genome annotation.</p>
<section id="annotation-summary" class="level3">
<h3 class="anchored" data-anchor-id="annotation-summary">Annotation summary</h3>
<p>The chromosome-associated assembly contained:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Annotation metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Chromosomal sequence length</td>
<td style="text-align: right;">3,635,575 bp</td>
</tr>
<tr class="even">
<td>Number of contigs</td>
<td style="text-align: right;">152</td>
</tr>
<tr class="odd">
<td>GC content</td>
<td style="text-align: right;">44.1%</td>
</tr>
<tr class="even">
<td>N50</td>
<td style="text-align: right;">271,950 bp</td>
</tr>
<tr class="odd">
<td>N90</td>
<td style="text-align: right;">73,406 bp</td>
</tr>
<tr class="even">
<td>Coding density</td>
<td style="text-align: right;">84.0%</td>
</tr>
<tr class="odd">
<td>CDSs</td>
<td style="text-align: right;">3,460</td>
</tr>
<tr class="even">
<td>tRNAs</td>
<td style="text-align: right;">84</td>
</tr>
<tr class="odd">
<td>rRNAs</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td>tmRNA</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td>ncRNAs</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td>ncRNA regions</td>
<td style="text-align: right;">37</td>
</tr>
<tr class="odd">
<td>Hypothetical proteins</td>
<td style="text-align: right;">504</td>
</tr>
<tr class="even">
<td>Pseudogenes</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>CRISPR arrays</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><br><br></p>
</section>
<section id="annotation-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="annotation-interpretation">Annotation interpretation</h3>
<p>The chromosome-associated genome showed a high coding density, with approximately <strong>84% of the sequence assigned to protein-coding regions</strong>.</p>
<p>Most predicted CDSs could be associated with known or putative biological functions, while <strong>504 proteins remained annotated as hypothetical</strong>, indicating coding regions for which no sufficiently specific functional assignment was available.</p>
<p>The Bakta annotation served as the central reference for downstream analyses, including antimicrobial-resistance screening, virulence assessment, stress-response genes, carbohydrate utilization, adhesion-associated proteins, exopolysaccharide loci and plantaricin-associated systems.</p>
</section>
</section>
<section id="genomic-safety-assessment" class="level2">
<h2 class="anchored" data-anchor-id="genomic-safety-assessment">Genomic safety assessment</h2>
<p>The E2C2 genome was screened for genomic features potentially relevant to microbial safety, including antimicrobial resistance determinants, virulence-associated genes, biogenic-amine pathways, prophages and plasmid-associated risk determinants.</p>
<section id="antimicrobial-resistance" class="level3">
<h3 class="anchored" data-anchor-id="antimicrobial-resistance">Antimicrobial resistance</h3>
<p>AMRFinderPlus detected <strong>no reportable antimicrobial resistance determinants</strong> in the analysed genome.</p>
<p>One additional determinant, <strong>clpL</strong>, was identified and classified as a heat-stress-associated gene rather than an antimicrobial-resistance gene.</p>
<p>The ClpL protein showed:</p>
<ul>
<li><strong>100% reference coverage</strong></li>
<li><strong>97.44% amino-acid identity</strong></li>
</ul>
<p>This protein is associated with cellular stress response and protein quality control.</p>
</section>
<section id="virulence-associated-genes" class="level3">
<h3 class="anchored" data-anchor-id="virulence-associated-genes">Virulence-associated genes</h3>
<p>Dedicated similarity screening against VFDB was used to investigate potential virulence-associated proteins.</p>
<p>Initial similarity hits were evaluated according to sequence identity, reference coverage and genomic context.</p>
<p>No convincing evidence for intact major virulence determinants was identified in the chromosome-associated genome.</p>
</section>
<section id="biogenic-amine-pathways" class="level3">
<h3 class="anchored" data-anchor-id="biogenic-amine-pathways">Biogenic amine pathways</h3>
<p>Targeted annotation and homology-based screening was performed for major pathways associated with biogenic-amine production.</p>
<p>No convincing homologues were detected for:</p>
<ul>
<li><strong>HdcA</strong> — histamine production</li>
<li><strong>Tdc</strong> — tyramine production</li>
<li><strong>Odc</strong> — ornithine-dependent putrescine production</li>
<li><strong>AguA</strong> — agmatine-dependent putrescine production</li>
<li><strong>Ldc</strong> — cadaverine production</li>
</ul>
<p>These results indicate that the major biogenic-amine pathways investigated were not detected genomically in E2C2.</p>
</section>
<section id="prophage-associated-regions" class="level3">
<h3 class="anchored" data-anchor-id="prophage-associated-regions">Prophage-associated regions</h3>
<p>geNomad identified <strong>seven candidate proviral regions</strong> integrated within the chromosome-associated assembly.</p>
<p>No antimicrobial-resistance determinants were identified within these regions.</p>
<p>Two short phage-associated proteins received an XhlA-like annotation during viral gene prediction. However, subsequent comparison against VFDB Set A proteins did not support their classification as known virulence-associated XhlA factors.</p>
<p>They were therefore treated as phage-associated XhlA-like proteins rather than confirmed haemolysins.</p>
</section>
<section id="plasmid-associated-safety-screening" class="level3">
<h3 class="anchored" data-anchor-id="plasmid-associated-safety-screening">Plasmid-associated safety screening</h3>
<p>The five MOB-suite-predicted plasmid-associated components were screened separately.</p>
<p>No reportable antimicrobial-resistance determinants were detected within the plasmid-associated sequences.</p>
<p>Dedicated VFDB searches also did not provide convincing evidence for intact plasmid-borne virulence determinants.</p>
</section>
<section id="genomic-safety-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="genomic-safety-interpretation">Genomic-safety interpretation</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Safety feature</th>
<th>Result</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Antimicrobial resistance determinants</td>
<td>No reportable AMR genes detected</td>
<td>No acquired AMR determinants identified in the targeted screening</td>
</tr>
<tr class="even">
<td>Major virulence-associated genes</td>
<td>No convincing major virulence factors detected</td>
<td>No strong evidence of major virulence-associated determinants</td>
</tr>
<tr class="odd">
<td>Biogenic amine pathways</td>
<td>Major pathways not detected</td>
<td>No clear histidine-, tyrosine-, ornithine-, agmatine- or lysine-decarboxylation pathways identified</td>
</tr>
<tr class="even">
<td>Prophage-associated regions</td>
<td>7 candidate regions</td>
<td>Prophage-like regions were detected, but no reportable AMR determinants were identified within them</td>
</tr>
<tr class="odd">
<td>Candidate plasmids</td>
<td>5 reconstructed components</td>
<td>No reportable AMR determinants and no convincing intact virulence-associated loci detected in candidate plasmid components</td>
</tr>
</tbody>
</table>
<p><br><br></p>
<p>The genomic safety screening produced an overall favourable profile for E2C2, with no convincing evidence for the major antimicrobial-resistance determinants, virulence factors or biogenic-amine pathways investigated.</p>
<p>However, genomic screening alone does not constitute a definitive demonstration of microbial safety.</p>
<p>Phenotypic testing, including antimicrobial susceptibility assays and appropriate functional or toxicological validation, would still be required before making conclusions regarding safety for food or probiotic applications.</p>
</section>
</section>
<section id="functional-and-technological-characterization" class="level2">
<h2 class="anchored" data-anchor-id="functional-and-technological-characterization">Functional and technological characterization</h2>
<section id="plantaricin-associated-locus" class="level3">
<h3 class="anchored" data-anchor-id="plantaricin-associated-locus">Plantaricin-associated locus</h3>
<p>The chromosome-associated genome was screened for bacteriocin-related functions, with particular attention to the plantaricin system.</p>
<p>A targeted comparison against plantaricin proteins from the reference strain <em>Lactiplantibacillus plantarum</em> WCFS1 identified eight high-confidence matches within a single genomic region on <code>contig_1</code>.</p>
<p>All detected reference proteins showed <strong>100% query coverage</strong>.</p>
<p>The main matches were:</p>
<ul>
<li><strong>PlnK:</strong> 98.25% identity</li>
<li><strong>PlnJ:</strong> 100% identity</li>
<li><strong>PlnA:</strong> 100% identity</li>
<li><strong>PlnB:</strong> 99.74% identity</li>
<li><strong>PlnC:</strong> 100% identity</li>
<li><strong>PlnD:</strong> 100% identity</li>
<li><strong>PlnF:</strong> 100% identity</li>
<li><strong>PlnE:</strong> 98.21% identity</li>
</ul>
</section>
<section id="locus-organization" class="level3">
<h3 class="anchored" data-anchor-id="locus-organization">Locus organization</h3>
<p>The plantaricin-associated region contained multiple functionally related components, including:</p>
<ul>
<li>the two-peptide bacteriocin system <strong>PlnJK</strong></li>
<li>the two-peptide bacteriocin system <strong>PlnEF</strong></li>
<li>the signaling and regulatory module <strong>PlnA–PlnB–PlnC/PlnD</strong></li>
<li>plantaricin biosynthesis-associated proteins <strong>PlnO</strong> and <strong>PlnQ</strong></li>
<li>bacteriocin immunity proteins related to <strong>PlnP</strong> and <strong>PlnI</strong></li>
</ul>
<p>The relevant genes were physically clustered within the same genomic region, supporting the presence of an organized plantaricin-associated locus rather than isolated bacteriocin-like genes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/plantaricin_locus_realcoords_v2.png" class="img-fluid figure-img"></p>
<figcaption>Real-coordinate organization of the plantaricin-associated locus identified in <em>Lactiplantibacillus plantarum</em> E2C2. The locus contains bacteriocin-associated genes, regulatory components, immunity proteins and biosynthesis-associated genes.</figcaption>
</figure>
</div>
<p>The E2C2 chromosome contains a <strong>highly conserved and apparently complete plantaricin regulatory and biosynthetic locus</strong>.</p>
<p>The simultaneous presence of the regulatory system, the PlnEF and PlnJK two-peptide bacteriocins, immunity-associated proteins and biosynthesis components provides strong genomic evidence for plantaricin-associated functional potential.</p>
<p>However, the genomic presence of this locus does not demonstrate bacteriocin production or antimicrobial activity under specific culture conditions.</p>
<p>Experimental validation would require expression analysis and/or direct antimicrobial activity assays.</p>
</section>
<section id="stress-tolerance" class="level3">
<h3 class="anchored" data-anchor-id="stress-tolerance">Stress tolerance</h3>
<p>The E2C2 chromosome contains a broad repertoire of genes potentially involved in adaptation to environmental and technological stress.</p>
<section id="heat-and-proteotoxic-stress" class="level4">
<h4 class="anchored" data-anchor-id="heat-and-proteotoxic-stress">Heat and proteotoxic stress</h4>
<p>Several major bacterial protein-quality-control systems were detected, including:</p>
<ul>
<li><strong>DnaK</strong></li>
<li><strong>DnaJ</strong></li>
<li><strong>GroEL</strong></li>
<li><strong>GroES</strong></li>
<li><strong>ClpB</strong></li>
<li><strong>ClpL</strong></li>
<li><strong>ClpX</strong></li>
<li>multiple ATP-dependent Clp protease components</li>
<li>multiple small heat-shock proteins</li>
</ul>
<p>These systems are involved in protein folding, refolding and degradation of damaged or misfolded proteins.</p>
<p>Their presence supports a strong genomic potential for adaptation to heat-associated and proteotoxic stress.</p>
</section>
<section id="oxidative-stress" class="level4">
<h4 class="anchored" data-anchor-id="oxidative-stress">Oxidative stress</h4>
<p>Multiple redox- and peroxide-associated proteins were also identified, including:</p>
<ul>
<li><strong>catalase</strong></li>
<li><strong>halo peroxidase</strong></li>
<li><strong>glutathione peroxidase</strong></li>
<li><strong>NADH peroxidase</strong></li>
<li>multiple <strong>thioredoxins</strong></li>
<li><strong>thioredoxin reductase</strong></li>
<li>a glutaredoxin-like protein (<strong>NrdH</strong>)</li>
</ul>
<p>Together, these genes indicate a diversified genomic repertoire potentially involved in protection against oxidative damage and maintenance of intracellular redox balance.</p>
</section>
<section id="acid-stress-and-glutamate-decarboxylase" class="level4">
<h4 class="anchored" data-anchor-id="acid-stress-and-glutamate-decarboxylase">Acid stress and glutamate decarboxylase</h4>
<p>Two coding sequences were annotated as <strong>glutamate decarboxylase beta</strong>:</p>
<ul>
<li><code>ONEOLA_01071</code></li>
<li><code>ONEOLA_01196</code></li>
</ul>
<p>Both are located on <code>contig_3</code>.</p>
<p>Glutamate decarboxylation consumes intracellular protons during conversion of glutamate to GABA and CO₂ and can therefore contribute to acid-stress adaptation.</p>
<p>However, no clear canonical <strong>GadC glutamate/GABA antiporter</strong> was identified in association with these genes.</p>
<p>In addition, the two GAD-like coding sequences occur within the large inverted-repeat structure previously identified on <code>contig_3</code>. They should therefore not automatically be interpreted as two independent functional copies.</p>
</section>
<section id="bile-associated-functions" class="level4">
<h4 class="anchored" data-anchor-id="bile-associated-functions">Bile-associated functions</h4>
<p>The E2C2 genome was screened for functions potentially associated with bile adaptation.</p>
<section id="bile-salt-hydrolase-like-locus" class="level5">
<h5 class="anchored" data-anchor-id="bile-salt-hydrolase-like-locus">Bile salt hydrolase-like locus</h5>
<p>A characterized bile salt hydrolase from <em>Lactiplantibacillus plantarum</em> WCFS1 was used as a reference for targeted homology searches.</p>
<p>Protein-level screening identified several BSH-like fragments, including matches with approximately:</p>
<ul>
<li><strong>95.16% amino-acid identity</strong></li>
<li><strong>99.04% amino-acid identity</strong></li>
</ul>
<p>A complementary TBLASTN search against the genomic assembly identified high-identity regions on <code>NODE_1</code> and <code>NODE_3</code>.</p>
<p>The strongest nucleotide-level translated matches included:</p>
<ul>
<li><code>NODE_1</code>: approximately <strong>99.16% identity</strong></li>
<li><code>NODE_3</code>: approximately <strong>92.89% identity</strong></li>
</ul>
<p>Together, these regions matched complementary portions of the WCFS1 BSH reference across nearly the full protein length.</p>
<p>However, the BSH-like sequence is fragmented across different assembly regions and is affected by the repeated/inverted architecture previously identified on <code>NODE_3</code>.</p>
<p>Therefore, the data strongly support the presence of a <strong>highly conserved BSH-like locus</strong>, but an intact functional BSH gene cannot be reconstructed unambiguously from the current short-read assembly.</p>
</section>
<section id="cell-envelope-adaptation" class="level5">
<h5 class="anchored" data-anchor-id="cell-envelope-adaptation">Cell-envelope adaptation</h5>
<p>A coordinated locus involved in D-alanylation of teichoic acids was identified on <code>contig_12</code>.</p>
<p>The region contains proteins corresponding to:</p>
<ul>
<li>D-Ala-teichoic acid biosynthesis</li>
<li>D-alanine–D-alanyl carrier protein ligase</li>
<li>teichoic-acid D-alanyltransferase</li>
<li>D-alanyl carrier protein</li>
<li><strong>DltD</strong></li>
</ul>
<p>This organization is consistent with a functional <strong>dlt-associated cell-envelope modification system</strong>.</p>
<p>D-alanylation of teichoic acids can alter bacterial surface charge and contribute to adaptation to membrane- and envelope-associated stress.</p>
</section>
<section id="bile-associated-interpretation" class="level5">
<h5 class="anchored" data-anchor-id="bile-associated-interpretation">Bile-associated interpretation</h5>
<p>E2C2 therefore carries multiple genomic features potentially relevant to bile-associated adaptation, including a strongly supported BSH-like locus and a coordinated dlt-associated cell-envelope modification system.</p>
<p>These genomic features indicate potential mechanisms for interaction with bile salts and envelope stress, but they do not demonstrate phenotypic bile tolerance.</p>
<p>Experimental growth or survival assays under defined bile concentrations would be required for functional validation.</p>
</section>
</section>
</section>
<section id="stress-response-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="stress-response-interpretation">Stress-response interpretation</h3>
<p>The E2C2 genome encodes a broad stress-response repertoire involving molecular chaperones, ATP-dependent proteases, peroxide-detoxification enzymes and thiol-redox systems.</p>
<p>Together with the bile-associated features described above, these results support substantial <strong>genomic potential for adaptation to heat, oxidative, acidic and bile-associated stress</strong>.</p>
<p>However, genomic potential does not demonstrate the actual tolerance of E2C2 under specific environmental or technological conditions.</p>
<p>Phenotypic growth and survival assays would be required for functional validation.</p>
</section>
<section id="carbohydrate-utilization" class="level3">
<h3 class="anchored" data-anchor-id="carbohydrate-utilization">Carbohydrate utilization</h3>
<p>Genome annotation revealed a broad repertoire of carbohydrate transport and utilization systems, including multiple components of the bacterial phosphotransferase system (PTS).</p>
<p>Detected PTS-associated functions included systems predicted to interact with several carbohydrate classes, including:</p>
<ul>
<li>mannose</li>
<li>cellobiose</li>
<li>β-glucosides</li>
<li>sugar alcohols</li>
<li>other hexose-associated substrates</li>
</ul>
<p>These systems combine carbohydrate uptake with substrate phosphorylation and are therefore directly connected to intracellular carbohydrate metabolism.</p>
<section id="mannose-associated-pts" class="level4">
<h4 class="anchored" data-anchor-id="mannose-associated-pts">Mannose-associated PTS</h4>
<p>A coordinated mannose-associated PTS region was identified containing multiple complementary components, including:</p>
<ul>
<li>mannose-specific <strong>EIIAB</strong></li>
<li>mannose-specific <strong>IIC</strong></li>
<li>mannose-specific <strong>IID</strong></li>
<li>additional <strong>EIIA</strong> and <strong>EIIB</strong> components</li>
</ul>
<p>The physical clustering of multiple transporter components supports the presence of an organized mannose-associated PTS system.</p>
</section>
<section id="β-glucoside-utilization" class="level4">
<h4 class="anchored" data-anchor-id="β-glucoside-utilization">β-glucoside utilization</h4>
<p>Several β-glucoside-associated PTS components and 6-phospho-beta-glucosidases were identified.</p>
<p>One particularly coherent locus on <code>contig_2</code> contains:</p>
<ul>
<li>a <strong>6-phospho-beta-glucosidase</strong></li>
<li><strong>BglP</strong>, a β-glucoside-specific PTS EIIBCA protein</li>
<li>a nearby <strong>PRD-domain regulatory protein</strong></li>
</ul>
<p>This organization is consistent with a functional module coupling:</p>
<ol type="1">
<li>β-glucoside uptake,</li>
<li>PTS-dependent phosphorylation,</li>
<li>intracellular hydrolysis of phosphorylated β-glucosides,</li>
<li>transcriptional or metabolic regulation.</li>
</ol>
<p>Additional β-glucoside-specific PTS components and 6-phospho-beta-glucosidases were identified elsewhere in the genome.</p>
</section>
<section id="cellobiose-associated-transport" class="level4">
<h4 class="anchored" data-anchor-id="cellobiose-associated-transport">Cellobiose-associated transport</h4>
<p>A <strong>cellobiose-specific PTS IIC component</strong> was also detected, providing additional evidence for genomic capacity to transport structurally different carbohydrate substrates.</p>
</section>
</section>
<section id="carbohydrate-utilization-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="carbohydrate-utilization-interpretation">Carbohydrate-utilization interpretation</h3>
<p>The E2C2 genome encodes a diverse carbohydrate-uptake repertoire, including multiple PTS systems and associated carbohydrate-metabolism enzymes.</p>
<p>This genomic organization suggests substantial potential for metabolic flexibility and utilization of different carbohydrate sources.</p>
<p>However, genomic presence alone does not demonstrate growth on individual substrates. Experimental carbon-source utilization assays would be required to determine which carbohydrates can actually support E2C2 growth under defined conditions.</p>
</section>
<section id="adhesion-and-cell-surface-interaction" class="level3">
<h3 class="anchored" data-anchor-id="adhesion-and-cell-surface-interaction">Adhesion and cell-surface interaction</h3>
<p>The E2C2 chromosome contains an extensive repertoire of proteins potentially involved in cell-surface organization and interaction with host-associated substrates.</p>
<p>Several complementary surface-associated systems were identified.</p>
<section id="sortase-dependent-surface-proteins" class="level4">
<h4 class="anchored" data-anchor-id="sortase-dependent-surface-proteins">Sortase-dependent surface proteins</h4>
<p>A <strong>Sortase A</strong> enzyme was identified together with multiple proteins containing LPXTG-type cell-wall anchoring features.</p>
<p>These proteins represent the classical Gram-positive mechanism for covalent attachment of extracellular proteins to the peptidoglycan layer.</p>
<p>The genomic coexistence of Sortase A and multiple LPXTG-associated proteins supports the presence of a functional sortase-dependent surface-protein system.</p>
</section>
<section id="mucbp-domain-proteins" class="level4">
<h4 class="anchored" data-anchor-id="mucbp-domain-proteins">MucBP-domain proteins</h4>
<p>Multiple proteins containing mucus-binding protein (<strong>MucBP</strong>) domains were detected.</p>
<p>Among them, <code>ONEOLA_00873</code> represents a particularly large MucBP-domain protein and is therefore a notable candidate for surface-associated interaction with mucus components.</p>
<p>However, this protein does not display a canonical LPXTG sorting motif and should not be interpreted as a conventional Sortase A-anchored protein.</p>
<p>Its architecture instead suggests a distinct surface-localization or membrane-association mechanism.</p>
</section>
<section id="mucus-adhesion-promoting-like-proteins" class="level4">
<h4 class="anchored" data-anchor-id="mucus-adhesion-promoting-like-proteins">Mucus adhesion-promoting-like proteins</h4>
<p>Two closely related proteins annotated as mucus adhesion-promoting proteins were identified within the same genomic region:</p>
<ul>
<li><code>ONEOLA_03112</code></li>
<li><code>ONEOLA_03115</code></li>
</ul>
<p>Their genomic organization and sequence similarity indicate the presence of two related members of the same surface-associated protein family.</p>
<p>Their annotation supports potential mucus-interaction capacity, although the surrounding genomic context indicates that these proteins may participate in a broader physiological system rather than a dedicated adhesion operon.</p>
</section>
<section id="additional-cell-surface-proteins" class="level4">
<h4 class="anchored" data-anchor-id="additional-cell-surface-proteins">Additional cell-surface proteins</h4>
<p>The genome also contains several additional proteins annotated as:</p>
<ul>
<li>cell-surface proteins</li>
<li>outer-surface proteins</li>
<li>LPXTG cell-wall anchor proteins</li>
<li>putative surface-associated proteins</li>
</ul>
<p>Together, these features indicate a structurally diverse bacterial surface proteome.</p>
</section>
</section>
<section id="adhesion-and-cell-surface-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="adhesion-and-cell-surface-interpretation">Adhesion and cell-surface interpretation</h3>
<p>E2C2 encodes multiple genomic systems potentially involved in cell-surface interaction, including Sortase A-dependent proteins, LPXTG-anchored proteins, MucBP-domain proteins and mucus adhesion-promoting-like proteins.</p>
<p>This repertoire supports substantial <strong>genomic potential for interaction with mucus and other biological surfaces</strong>.</p>
<p>However, gene annotation and predicted protein architecture cannot demonstrate actual adhesion efficiency.</p>
<p>Direct mucus-binding, epithelial-cell adhesion or aggregation assays would be required to establish the corresponding phenotype.</p>
</section>
<section id="exopolysaccharide-and-surface-polysaccharide-potential" class="level3">
<h3 class="anchored" data-anchor-id="exopolysaccharide-and-surface-polysaccharide-potential">Exopolysaccharide and surface-polysaccharide potential</h3>
<p>The E2C2 chromosome contains multiple genomic regions associated with polysaccharide biosynthesis.</p>
<p>A dedicated cluster-detection workflow identified <strong>three candidate polysaccharide biosynthesis loci</strong>, including two high-confidence regions and one medium-confidence region.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/eps_loci_v1.png" class="img-fluid figure-img"></p>
<figcaption>Organization of three candidate EPS-associated loci identified in <em>Lactiplantibacillus plantarum</em> E2C2. Genes are shown using real genomic coordinates and grouped by predicted functional category.</figcaption>
</figure>
</div>
<section id="eps-cluster-1" class="level4">
<h4 class="anchored" data-anchor-id="eps-cluster-1">EPS cluster 1</h4>
<p><code>EPS_cluster_1</code> is located on <code>contig_2</code> and spans approximately <strong>15.9 kb</strong>.</p>
<p>The region contains 13 coding sequences and includes genes associated with:</p>
<ul>
<li>glycosyltransferases</li>
<li>polysaccharide biosynthesis</li>
<li>oligosaccharide transport</li>
<li>repeat-unit transport</li>
<li>polysaccharide-associated processing</li>
</ul>
<p>The cluster was classified as <strong>MEDIUM_CONFIDENCE</strong> because it contains multiple complementary polysaccharide-associated functions, although the regulatory and precursor-synthesis architecture is less complete than in the two higher-confidence loci.</p>
</section>
<section id="eps-cluster-2" class="level4">
<h4 class="anchored" data-anchor-id="eps-cluster-2">EPS cluster 2</h4>
<p>A second region on <code>contig_2</code>, spanning approximately <strong>13.4 kb</strong>, was classified as <strong>HIGH_CONFIDENCE</strong>.</p>
<p>This locus contains 14 coding sequences and combines all major functional categories detected by the pipeline:</p>
<ul>
<li>glycosyltransferases</li>
<li>polysaccharide polymerization</li>
<li>precursor modification</li>
<li>regulation</li>
<li>transport</li>
</ul>
<p>Notable components include:</p>
<ul>
<li>repeat-unit transporter</li>
<li>multiple glycosyltransferases</li>
<li>polysaccharide polymerase</li>
<li>nucleotide-sugar modification enzymes</li>
<li><strong>EpsD</strong></li>
<li><strong>CpsC</strong></li>
</ul>
<p>The coordinated presence of synthesis, regulation, polymerization and transport functions strongly supports the interpretation of this region as an organized surface- or extracellular-polysaccharide biosynthesis locus.</p>
</section>
<section id="eps-cluster-3" class="level4">
<h4 class="anchored" data-anchor-id="eps-cluster-3">EPS cluster 3</h4>
<p><code>EPS_cluster_3</code> is located on <code>contig_9</code> and spans approximately <strong>9.7 kb</strong>.</p>
<p>The region contains 10 coding sequences and was also classified as <strong>HIGH_CONFIDENCE</strong>.</p>
<p>Its organization includes:</p>
<ul>
<li><strong>CpsC</strong></li>
<li><strong>EpsD</strong></li>
<li>a tyrosine-protein phosphatase</li>
<li>nucleotide-sugar modification enzymes</li>
<li>multiple glycosyltransferases</li>
<li>a polysaccharide polymerase</li>
<li>additional polysaccharide biosynthesis proteins</li>
</ul>
<p>The compact organization of these genes within a continuous genomic region provides strong evidence for a second distinct polysaccharide biosynthesis system.</p>
</section>
</section>
<section id="exopolysaccharide-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="exopolysaccharide-interpretation">Exopolysaccharide interpretation</h3>
<p>E2C2 therefore carries at least <strong>two high-confidence and one additional medium-confidence polysaccharide biosynthesis loci</strong>.</p>
<p>The coexistence of glycosyltransferases, precursor-modification enzymes, polymerization machinery, transport components and EpsD/CpsC regulatory proteins supports substantial genomic potential for the synthesis and export of complex surface or extracellular polysaccharides.</p>
<p>These loci may contribute to cell-surface properties, environmental interactions, stress protection and technological characteristics of the strain.</p>
<p>However, genome analysis cannot determine the amount, chemical composition or physical properties of the polysaccharides produced.</p>
<p>Experimental EPS isolation, quantification and structural characterization would therefore be required to establish the corresponding phenotype.</p>
</section>
<section id="technological-traits" class="level3">
<h3 class="anchored" data-anchor-id="technological-traits">Technological traits</h3>
<p>The E2C2 genome contains several metabolic and proteolytic features potentially relevant to food fermentation and industrial biotechnology. <br><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Technological trait</th>
<th>Genomic evidence</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lactate metabolism</td>
<td>Multiple L-lactate and D-lactate dehydrogenase genes</td>
<td>Supports genomic capacity for lactate production and interconversion</td>
</tr>
<tr class="even">
<td>Acetoin-associated metabolism</td>
<td>Alpha-acetolactate synthase, alpha-acetolactate decarboxylase and an acetoin transporter</td>
<td>Supports potential acetoin-associated metabolic activity</td>
</tr>
<tr class="odd">
<td>Peptide uptake</td>
<td>Multiple oligopeptide and dipeptide transport components</td>
<td>Supports efficient acquisition of extracellular peptides</td>
</tr>
<tr class="even">
<td>Intracellular proteolysis</td>
<td>Multiple aminopeptidases, dipeptidases, PepO-like and Xaa-Pro peptidases</td>
<td>Indicates a broad intracellular peptide-processing repertoire</td>
</tr>
<tr class="odd">
<td>Cell-surface interaction</td>
<td>Sortase-dependent proteins, MucBP-domain proteins and mucus adhesion-promoting-like proteins</td>
<td>Supports potential interaction with host-associated or food-associated surfaces</td>
</tr>
<tr class="even">
<td>EPS-associated potential</td>
<td>Three candidate polysaccharide biosynthesis loci, including two high-confidence clusters</td>
<td>Supports substantial surface-polysaccharide biosynthetic potential</td>
</tr>
<tr class="odd">
<td>Plantaricin-associated system</td>
<td>Regulatory, immunity and bacteriocin-associated genes including PlnEF and PlnJK</td>
<td>Supports genomic potential for plantaricin-associated antimicrobial activity</td>
</tr>
</tbody>
</table>
<p><br><br></p>
<section id="lactate-metabolism" class="level4">
<h4 class="anchored" data-anchor-id="lactate-metabolism">Lactate metabolism</h4>
<p>Multiple lactate dehydrogenases were identified, including:</p>
<ul>
<li>three <strong>L-lactate dehydrogenases</strong></li>
<li>two <strong>D-lactate dehydrogenases</strong></li>
</ul>
<p>These enzymes support genomic capacity for formation and metabolism of both L- and D-lactate.</p>
<p>The presence of multiple lactate-associated enzymes suggests a relatively diversified pyruvate/lactate metabolic network.</p>
<p>From a technological perspective, this is relevant because lactate production contributes directly to fermentation acidification, while the relative production of L- and D-lactate can vary according to strain, substrate and cultivation conditions.</p>
</section>
<section id="acetoin-associated-metabolism" class="level4">
<h4 class="anchored" data-anchor-id="acetoin-associated-metabolism">Acetoin-associated metabolism</h4>
<p>A coherent pathway associated with acetoin formation was identified.</p>
<p>The main enzymatic components include:</p>
<ul>
<li><strong>alpha-acetolactate synthase</strong></li>
<li><strong>alpha-acetolactate decarboxylase</strong></li>
</ul>
<p>The predicted metabolic sequence is:</p>
<p><code>pyruvate → alpha-acetolactate → acetoin</code></p>
<p>Additional genes encode:</p>
<ul>
<li>an acetoin ABC transporter permease</li>
<li>acetoin-associated GntR-family regulatory proteins</li>
</ul>
<p>Together, these features provide strong genomic evidence for potential acetoin formation and handling.</p>
<p>Alpha-acetolactate may also contribute indirectly to diacetyl formation under appropriate fermentation conditions.</p>
<p>However, the genome alone cannot predict the quantities of acetoin or diacetyl produced during fermentation.</p>
</section>
<section id="peptide-uptake-and-intracellular-proteolysis" class="level4">
<h4 class="anchored" data-anchor-id="peptide-uptake-and-intracellular-proteolysis">Peptide uptake and intracellular proteolysis</h4>
<p>E2C2 also encodes an extensive peptide-utilization repertoire.</p>
<p>Several components involved in peptide uptake were identified, including:</p>
<ul>
<li>oligopeptide ABC transporter components</li>
<li>dipeptide transport components</li>
<li>peptide-binding proteins</li>
<li>amino-acid/peptide transporters</li>
</ul>
<p>The intracellular proteolytic repertoire includes numerous enzymes such as:</p>
<ul>
<li>aminopeptidases</li>
<li>dipeptidases</li>
<li>proline iminopeptidases</li>
<li>Xaa-Pro peptidases</li>
<li><strong>PepO</strong> endopeptidases</li>
<li>oligoendopeptidase F</li>
<li>Peptidase T</li>
</ul>
<p>This combination supports substantial genomic potential for uptake and intracellular degradation of environmental peptides.</p>
<p>No clear canonical <strong>PrtP/lactocepin-type cell-envelope proteinase</strong> was identified during the targeted screening.</p>
<p>Therefore, E2C2 may rely primarily on peptides already available in the environment or generated by external proteolysis rather than on extensive primary degradation of intact extracellular proteins.</p>
</section>
</section>
<section id="technological-traits-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="technological-traits-interpretation">Technological-traits interpretation</h3>
<p>The technological-trait screening indicates that E2C2 possesses genomic potential relevant to several fermentation-associated processes, including:</p>
<ul>
<li>lactate formation and acidification</li>
<li>acetoin-associated aroma metabolism</li>
<li>peptide acquisition</li>
<li>intracellular peptide degradation</li>
</ul>
<p>These features make the strain genomically interesting from a food-biotechnology perspective.</p>
<p>However, the genomic results describe metabolic potential rather than fermentation performance.</p>
<p>Experimental measurements of acidification kinetics, L/D-lactate ratios, volatile compounds and proteolytic activity would be required to characterize the technological phenotype directly.</p>
</section>
</section>
<section id="comparative-genomics" class="level2">
<h2 class="anchored" data-anchor-id="comparative-genomics">Comparative genomics</h2>
<p>A comparative pangenome analysis was performed to place E2C2 within a strain-level genomic context.</p>
<p>The E2C2 genome was compared with two additional <em>Lactiplantibacillus plantarum</em> genomes, A6 and B21, using Panaroo-based orthologous gene clustering.</p>
<p>Across the three genomes, a total of <strong>3,588 gene clusters</strong> were identified.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/comparative_traits_heatmap.png" class="img-fluid figure-img"></p>
<figcaption>Comparative genomic traits across <em>Lactiplantibacillus plantarum</em> strains E2C2, A6 and B21. The heatmap summarizes presence, partial/divergent conservation or non-detection of selected functional modules in the comparative analysis.</figcaption>
</figure>
</div>
<p><br><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Comparative feature</th>
<th style="text-align: right;">E2C2</th>
<th style="text-align: right;">A6</th>
<th style="text-align: right;">B21</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Core gene clusters</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Present</td>
<td>2,576 clusters shared by all three strains</td>
</tr>
<tr class="even">
<td>Strain-specific clusters</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">234</td>
<td>E2C2 carries the largest strain-specific gene set in this comparison</td>
</tr>
<tr class="odd">
<td>Conserved EPS locus</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Present</td>
<td>One EPS-associated locus is conserved across all three strains</td>
</tr>
<tr class="even">
<td>Variable EPS locus</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Not detected</td>
<td style="text-align: right;">Not detected</td>
<td>E2C2 carries an additional variable EPS-associated region</td>
</tr>
<tr class="odd">
<td>Plantaricin system</td>
<td style="text-align: right;">Complete-like</td>
<td style="text-align: right;">Partial</td>
<td style="text-align: right;">Complete-like</td>
<td>E2C2 and B21 retain a broader plantaricin-associated gene repertoire than A6</td>
</tr>
<tr class="even">
<td>Major adhesion-associated proteins</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Present</td>
<td>Major surface-interaction determinants are broadly conserved</td>
</tr>
<tr class="odd">
<td>β-glucoside utilization module</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Not detected</td>
<td style="text-align: right;">Not detected</td>
<td>E2C2-specific in this three-strain comparison</td>
</tr>
<tr class="even">
<td>Dicarboxylate-associated module</td>
<td style="text-align: right;">Present</td>
<td style="text-align: right;">Not detected</td>
<td style="text-align: right;">Not detected</td>
<td>E2C2-specific accessory metabolic feature</td>
</tr>
<tr class="odd">
<td>E2C2-specific mobile/prophage-associated clusters</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
<td>Most are concentrated on contig_11 and contig_8</td>
</tr>
</tbody>
</table>
<p><br><br></p>
<section id="pangenome-structure" class="level3">
<h3 class="anchored" data-anchor-id="pangenome-structure">Pangenome structure</h3>
<p>Panaroo classified:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category</th>
<th style="text-align: right;">Gene clusters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Core</td>
<td style="text-align: right;">2,576</td>
</tr>
<tr class="even">
<td>Shell / accessory</td>
<td style="text-align: right;">1,012</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">3,588</td>
</tr>
</tbody>
</table>
<p>The <strong>2,576 core gene clusters</strong> are shared by E2C2, A6 and B21 and represent approximately <strong>72% of the gene clusters detected in this three-strain comparison</strong>.</p>
<p>Because only three genomes were analyzed, the Panaroo frequency categories should be interpreted specifically within this dataset and not as an estimate of the complete <em>L. plantarum</em> species pangenome.</p>
</section>
<section id="strain-specific-gene-clusters" class="level3">
<h3 class="anchored" data-anchor-id="strain-specific-gene-clusters">Strain-specific gene clusters</h3>
<p>Presence/absence analysis identified:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Distribution</th>
<th style="text-align: right;">Gene clusters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E2C2 only</td>
<td style="text-align: right;">273</td>
</tr>
<tr class="even">
<td>A6 only</td>
<td style="text-align: right;">135</td>
</tr>
<tr class="odd">
<td>B21 only</td>
<td style="text-align: right;">234</td>
</tr>
<tr class="even">
<td>E2C2 + A6</td>
<td style="text-align: right;">142</td>
</tr>
<tr class="odd">
<td>E2C2 + B21</td>
<td style="text-align: right;">146</td>
</tr>
<tr class="even">
<td>A6 + B21</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="odd">
<td>Shared by all three</td>
<td style="text-align: right;">2,576</td>
</tr>
</tbody>
</table>
<p>E2C2 therefore displayed the largest number of strain-specific clusters in this three-genome comparison.</p>
<p>Importantly, these <strong>273 E2C2-specific clusters</strong> should not be interpreted as genes unique to E2C2 across the entire species.</p>
<p>They represent orthologous clusters detected in E2C2 but not assigned to corresponding clusters in A6 or B21 under the conditions of this comparison.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/pangenome_composition.png" class="img-fluid figure-img"></p>
<figcaption>Pangenome composition across <em>Lactiplantibacillus plantarum</em> strains E2C2, A6 and B21. Bars represent the distribution of orthologous gene clusters among core and strain-specific/shared accessory categories.</figcaption>
</figure>
</div>
</section>
<section id="surface-polysaccharide-diversification" class="level3">
<h3 class="anchored" data-anchor-id="surface-polysaccharide-diversification">Surface-polysaccharide diversification</h3>
<p>Comparative analysis revealed two contrasting patterns among the polysaccharide biosynthesis loci.</p>
<p>A polysaccharide biosynthesis locus corresponding to the high-confidence region identified on <code>contig_9</code> was broadly conserved across all three strains.</p>
<p>In contrast, the large polysaccharide-associated region on <code>contig_2</code> contained multiple genes assigned to E2C2-specific clusters.</p>
<p>This region includes functions associated with:</p>
<ul>
<li>glycosyltransferases</li>
<li>polysaccharide polymerization</li>
<li>repeat-unit transport</li>
<li>flippase-mediated transport</li>
<li>precursor modification</li>
<li>EpsD/CpsC-associated regulation</li>
</ul>
<p>This suggests that E2C2 possesses a conserved polysaccharide biosynthesis backbone together with an additional, more variable accessory region.</p>
<p>Such organization is consistent with substantial strain-level diversification of surface or extracellular polysaccharide biosynthesis.</p>
</section>
<section id="plantaricin-locus-conservation" class="level3">
<h3 class="anchored" data-anchor-id="plantaricin-locus-conservation">Plantaricin locus conservation</h3>
<p>The plantaricin-associated system showed an intermediate pattern of conservation.</p>
<p>Components of the PlnEF and PlnJK bacteriocin systems and their regulatory machinery were detected across the comparative dataset, but the complete orthologous organization was not identical among the three strains.</p>
<p>E2C2 and B21 shared a more complete corresponding plantaricin module, whereas A6 showed only partial conservation of the same orthologous structure.</p>
<p>The results therefore suggest that bacteriocin-associated functionality is broadly conserved while the detailed architecture of the locus varies between strains.</p>
</section>
<section id="adhesion-associated-proteins" class="level3">
<h3 class="anchored" data-anchor-id="adhesion-associated-proteins">Adhesion-associated proteins</h3>
<p>The major adhesion and cell-surface proteins examined were broadly conserved across E2C2, A6 and B21.</p>
<p>These included orthologs corresponding to:</p>
<ul>
<li>mucus adhesion-promoting-like proteins</li>
<li>major MucBP-domain proteins</li>
<li>LPXTG-associated surface proteins</li>
</ul>
<p>Unlike the variable EPS region, the principal adhesion-associated systems analyzed therefore appear to represent largely conserved features among the three strains rather than E2C2-specific adaptations.</p>
</section>
<section id="e2c2-specific-β-glucoside-utilization-module" class="level3">
<h3 class="anchored" data-anchor-id="e2c2-specific-β-glucoside-utilization-module">E2C2-specific β-glucoside utilization module</h3>
<p>One of the most interesting metabolic differences involved a coherent β-glucoside utilization module.</p>
<p>E2C2 contains an accessory genomic region comprising:</p>
<ul>
<li>a <strong>β-glucoside-specific PTS transporter BglP</strong></li>
<li>a <strong>6-phospho-beta-glucosidase</strong></li>
<li>a <strong>PRD-domain regulatory protein</strong></li>
</ul>
<p>No corresponding orthologous clusters were detected for this complete module in A6 or B21.</p>
<p>The genomic organization combines transport, phosphorylation, intracellular degradation and regulation, making it a functionally coherent carbohydrate-utilization module.</p>
<p>This result suggests potential strain-level differentiation in β-glucoside metabolism.</p>
<p>However, it does not demonstrate that E2C2 can utilize substrates that A6 or B21 cannot; comparative growth experiments would be required to establish the phenotype.</p>
</section>
<section id="dicarboxylate-associated-metabolic-module" class="level3">
<h3 class="anchored" data-anchor-id="dicarboxylate-associated-metabolic-module">Dicarboxylate-associated metabolic module</h3>
<p>A second E2C2-specific metabolic region contained:</p>
<ul>
<li>a <strong>2-hydroxyacid dehydrogenase</strong></li>
<li>a <strong>sodium-dependent dicarboxylate transporter SdcS</strong></li>
</ul>
<p>Corresponding orthologous clusters were not detected in A6 or B21.</p>
<p>This represents an additional example of accessory metabolic differentiation in E2C2, although the physiological consequences of the locus remain to be experimentally established.</p>
</section>
<section id="mobile-and-prophage-associated-diversity" class="level3">
<h3 class="anchored" data-anchor-id="mobile-and-prophage-associated-diversity">Mobile and prophage-associated diversity</h3>
<p>A substantial component of the E2C2 accessory genome was associated with mobile genetic elements.</p>
<p>Among the E2C2-specific clusters, <strong>40</strong> were classified as mobile- or phage-associated.</p>
<p>Most of these were concentrated in two genomic regions:</p>
<ul>
<li><code>contig_11</code></li>
<li><code>contig_8</code></li>
</ul>
<p>Previous analysis showed that <strong>34 of the 40 mobile-associated E2C2-specific clusters</strong> occur on these two contigs.</p>
<p>This concentration suggests that much of the mobile-genome differentiation between E2C2 and the comparison strains originates from a limited number of large mobile or prophage-associated genomic regions rather than from many independent differences distributed throughout the chromosome.</p>
</section>
<section id="comparative-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="comparative-interpretation">Comparative interpretation</h3>
<p>The comparative analysis separates two components of the E2C2 genome.</p>
<p>The conserved component includes much of the fundamental cellular machinery together with several adhesion-associated functions and one major polysaccharide biosynthesis system.</p>
<p>The accessory component includes more variable features such as:</p>
<ul>
<li>a strain-variable polysaccharide biosynthesis region</li>
<li>a β-glucoside utilization module</li>
<li>a dicarboxylate transport/metabolic module</li>
<li>numerous mobile and prophage-associated gene clusters</li>
</ul>
<p>E2C2 therefore appears to combine a conserved <em>L. plantarum</em> genomic backbone with a substantial accessory component affecting surface-polysaccharide biosynthesis, carbohydrate metabolism and genome plasticity.</p>
<p>These differences provide candidate mechanisms for strain-level ecological or technological specialization, but genomic comparisons alone cannot establish their phenotypic consequences.</p>
</section>
</section>
<section id="workflow-design" class="level2">
<h2 class="anchored" data-anchor-id="workflow-design">Workflow design</h2>
<p>The project was structured as a modular genomic analysis pipeline:</p>
<pre class="text"><code>Raw FASTQ
    ↓
FastQC
    ↓
fastp
    ↓
Clean FASTQ
    ↓
FastQC + MultiQC
    ↓
Kraken2
    ↓
De novo assembly
    ↓
Assembly quality assessment
    ↓
Read mapping
    ↓
Genome quality assessment
    ↓
Genome annotation
    ↓
Safety screening
    ↓
Functional screening
    ↓
Comparative genomics</code></pre>
<p>Bioinformatic analysis developed as an independent portfolio project focused on workflows and data relevant to the microbiology and biotechnology activities of Sacco System.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>